[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@pendle/core/contracts/=lib/pendle-core-v2-public/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    '@solady/contracts/=lib/solady/src/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
